const permission = {
  admin: {
    addUser: true,
    ListUser: true,
    deleteUser: true,
    updateUser: true,
    addClient: true,
    ListClient: true,
    deleteClient: true,
    updateClient: true,
    ListTask: true,
    addTask: true,
    updateTask: true,
    deleteTask: true,
    ListDocument: true,
    addDocument: true,
    deleteDocument: true,
    updateDocument: true,
  },
  user: {
    ListUser: true,
    addUser: false,
    deleteUser: false,
    updateUser: false,
    addClient: false,
    ListClient: true,
    deleteClient: false,
    updateClient: false,
    ListTask: true,
    addTask: false,
    updateTask: false,
    deleteTask: false,
    ListDocument: true,
    addDocument: true,
    deleteDocument: false,
    updateDocument: false,
  },
};

export const {admin,employee} = permission